from dataclasses import dataclass, field
from typing import List

@dataclass
class Block:
    name: str
    width: float
    height: float
    x: float = 0.0
    y: float = 0.0
    # Heat generated by the component
    power_watts: float = 10.0

    def area(self) -> float:
        return self.width * self.height

@dataclass
class Net:
    name: str
    connected_blocks: List[Block] = field(default_factory=list)

@dataclass
class Floorplan:
    blocks: List[Block]
    nets: List[Net]
    chip_width: float = 400.0
    chip_height: float = 400.0
    
    def get_block(self, name: str) -> Block:
        for b in self.blocks:
            if b.name == name:
                return b
        raise ValueError(f"Block {name} not found")